server:
  port: 9527
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名去路由
      routes: # /// 路由的第一种配置
        - id: city-service
          uri: lb://CITY-SERVICE
          predicates:
            - Path=/city-service/**
          filters:
            - StripPrefix=1
        - id: weather-service
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/weather-service/**
          filters:
            - StripPrefix=1
#    config:
#      label: main
#      name: config
#      profile: dev
#      uri: http://localhost:3344
#      username: user
#      password: 92d7feb0-41fd-47c6-aab2-fcb5ca4ba0b7
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka1.host}:${eureka1.port}/eureka,http://${eureka2.host}:${eureka2.port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"