server:
  port: 33472
spring:
  redis:
    host: 8.142.15.127
    port: 6379
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.142.15.127:3306/weather?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: cDe3@wsx
#  cloud:
#    config:
#      label: main
#      name: config
#      profile: dev
#      uri: http://localhost:3344
#      username: user
#      password: 92d7feb0-41fd-47c6-aab2-fcb5ca4ba0b7
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: city-service-33472
    prefer-ip-address: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"