server:
  port: 3344
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:ShunyiChen/autoparts-config-repo.git
          search-paths:
            - autoparts-config-repo
      label: main
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port} # 5672
    user: guest
    password: guest

eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://${eureka1.host}:${eureka1.port}/eureka,http://${eureka2.host}:${eureka2.port}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

